- name: CentOS 7 - set php.ini options
  when:
    aspects_php_config is defined and
    item.value.enable == True and
    ansible_distribution == "CentOS" and
    ansible_distribution_major_version == "7" and
    item.value.target.CentOS is defined and
    item.value.target.CentOS.7 is defined
  ini_file:
    state: "present"
    dest: "{{ item.value.target.CentOS.7 }}"
    option: "{{ item.value.name }}"
    value: "{{ item.value.value }}"
    section: "{{ item.value.section }}"
    owner: 0
    group: 0
    mode: "600"
  with_dict: "{{ aspects_php_config }}"
  tags:
    - aspects_php
    - aspects_php_config

- name: Ubuntu 14.04 - set php.ini options
  when:
    aspects_php_config is defined and
    item.value.enable == True and
    ansible_distribution == "Ubuntu" and
    ansible_distribution_version == "14.04" and
    item.value.target.Ubuntu is defined and
    item.value.target.Ubuntu.1404 is defined
  ini_file:
    state: "present"
    dest: "{{ item.value.target.Ubuntu.1404 }}"
    option: "{{ item.value.name }}"
    value: "{{ item.value.value }}"
    section: "{{ item.value.section }}"
    owner: 0
    group: 0
    mode: "600"
  with_dict: "{{ aspects_php_config }}"
  tags:
    - aspects_php
    - aspects_php_config

- name: Ubuntu 16.04 - set php.ini options
  when:
    aspects_php_config is defined and
    item.value.enable == True and
    ansible_distribution == "Ubuntu" and
    ansible_distribution_version == "16.04" and
    item.value.target.Ubuntu is defined and
    item.value.target.Ubuntu.1604 is defined
  ini_file:
    state: "present"
    dest: "{{ item.value.target.Ubuntu.1604 }}"
    option: "{{ item.value.name }}"
    value: "{{ item.value.value }}"
    section: "{{ item.value.section }}"
    owner: 0
    group: 0
    mode: "600"
  with_dict: "{{ aspects_php_config }}"
  tags:
    - aspects_php
    - aspects_php_config

- name: Debian 9 - set php.ini options
  when:
    aspects_php_config is defined and
    item.value.enable == True and
    ansible_distribution == "Debian" and
    ansible_distribution_major_version == "9" and
    item.value.target.Debian is defined and
    item.value.target.Debian.9 is defined
  ini_file:
    state: "present"
    dest: "{{ item.value.target.Debian.9 }}"
    option: "{{ item.value.name }}"
    value: "{{ item.value.value }}"
    section: "{{ item.value.section }}"
    owner: 0
    group: 0
    mode: "600"
  with_dict: "{{ aspects_php_config }}"
  tags:
    - aspects_php
    - aspects_php_config
