---
- name: "Set ini file configuration"
  include: iniSetConfiguration.yml
  tags:
    - aspects_php
    - aspects_php_config

- name: "Remove ini file configuration"
  include: iniRemoveConfiguration.yml
  tags:
    - aspects_php
    - aspects_php_config

- name: "Include 'Remove files listed in aspects_php_remove_package_managed_ini_files' tasks"
  include: removePackageManagedINIFiles.yml
  tags:
    - aspects_php
    - aspects_php_remove_package_managed_ini_files
