---
# This will fail if php-devel and php-pear are not installed.
- name: "Install PEAR or PECL package"
  when: item.value.state == "present" or item.value.state == "latest"
  pear:
    name: "{{ item.value.name }}"
    state: "{{ item.value.state }}"
  loop: "{{ aspects_php_pecl_packages|dict2items }}"
  tags:
    - aspects_php
    - aspects_php_pecl
    - aspects_php_pecl_packages

- name: "Remove PEAR or PECL package"
  when:
    - item.value.state == "absent"
  pear:
    name: "{{ item.value.name }}"
    state: "{{ item.value.state }}"
  loop: "{{ aspects_php_pecl_packages|dict2items }}"
  tags:
    - aspects_php
    - aspects_php_pecl
    - aspects_php_pecl_packages
