---

- name: Get mod link state.
  stat:
    path: "{{ item.value.link }}"
    follow: yes
  with_dict: "{{ aspects_php_modules }}"
  register: modlinkstate
  tags:
  - aspects_php
  - aspects_php_modules

- name: Enable module
  when:
    modlinkstate|skipped == False and
    item.item.value.state == "enabled" and
    item.stat.exists == False
  shell: /usr/sbin/php5enmod {{ item.item.value.name }}
  with_items: "{{ modlinkstate.results }}"
  tags:
  - aspects_php
  - aspects_php_modules

- name: Disable module
  when:
    modlinkstate|skipped == False and
    item.stat.exists == True and
    item.item.value.state == "disabled"
  shell: /usr/sbin/php5dismod {{ item.item.value.name }}
  with_items: "{{ modlinkstate.results }}"
  tags:
  - aspects_php
  - aspects_php_modules
