---
- name: yum - Remove php packages on CentOS 7
  when:
    (
      ansible_distribution == "CentOS" and
      ansible_distribution_major_version == "7" and
      item.value.state == "absent"
    )
  yum:
    name: "{{ item.value.CentOS.7 }}"
    state: "{{ item.value.state }}"
  with_dict: "{{ aspects_php_packages }}"
  tags:
    - aspects_php
    - aspects_php_package_remove
    - aspects_php_package_remove_yum
